repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.5.7
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
            args: [--check, --diff]

    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-yaml
          - id: check-toml
          - id: check-json

    # Auto-add hook removed to prevent conflicts
    # Use 'make commit' instead for auto-fixing and staging
