# 5500 Full Stack Services
# This compose file contains all services: backend, database, and pgAdmin

services:
  # FastAPI Backend Application
  backend:
    build: .
    container_name: 5500_backend
    env_file:
      - .env
    environment:
      # Override database host for Docker (use 'database' instead of 'localhost')
      - DATABASE_URL=postgresql+psycopg://class_connect_user:class_connect_password@database:5432/class_connect_db
      # Override app environment for Docker
      - APP_ENV=production
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    networks:
      - 5500_network
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: 5500_database
    environment:
      POSTGRES_DB: class_connect_db
      POSTGRES_USER: class_connect_user
      POSTGRES_PASSWORD: class_connect_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - 5500_postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - 5500_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qr_survey_user -d qr_survey_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 5500_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@qrsurvey.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    volumes:
      - 5500_pgadmin_data:/var/lib/pgadmin
    networks:
      - 5500_network
    depends_on:
      - database
    restart: unless-stopped

volumes:
  5500_postgres_data:
  5500_pgadmin_data:

networks:
  5500_network:
    driver: bridge

