"""add survey templates and update sessions

Revision ID: f69a8eb6dc62
Revises: bb4ac7a51c19
Create Date: 2025-10-22 11:02:32.453993

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f69a8eb6dc62"
down_revision: Union[str, Sequence[str], None] = "bb4ac7a51c19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "survey_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("questions_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_survey_template_title", "survey_templates", ["title"], unique=True)
    op.add_column("sessions", sa.Column("survey_template_id", sa.String(length=36), nullable=False))
    op.create_foreign_key(
        None, "sessions", "survey_templates", ["survey_template_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "survey_template_id")
    op.drop_index("ix_survey_template_title", table_name="survey_templates")
    op.drop_table("survey_templates")
    # ### end Alembic commands ###
